language: node_js
sudo: false
node_js:
  - "6"
cache:
  yarn: true
branches:
  only:
    - master
install:
  - npm install
  - ./node_modules/.bin/webpack --config webpack.config.js
script:
  - npm run build
  - npm start
